#include <iostream>
using namespace std;

int main(){
	cout << endl;
	cout << "                                         do. 									" << endl;
	cout << "                                        :NOX 									" << endl;
	cout << "                                       ,NOM@: 									" << endl;
	cout << "                                       :NNNN: 									" << endl;
	cout << "                                       :XXXON 									" << endl;
	cout << "                                       :XoXXX. 								" << endl;
	cout << "                                       MM;ONO: 								" << endl;
	cout << "  .oob..                              :MMO;MOM 								" << endl;
	cout << " dXOXYYNNb.                          ,NNMX:MXN 								" << endl;
	cout << " Mo\"\'  \'\':Nbb                        dNMMN MNN: 							" << endl;
	cout << " Mo  \'O;; \':Mb.                     ,MXMNM MNX: 								" << endl;
	cout << " @O :;XXMN..\'X@b.                  ,NXOMXM MNX: 								" << endl;
	cout << " YX;;NMMMM@M;;OM@o.                dXOOMMN:MNX: 								" << endl;
	cout << " \'MOONM@@@MMN:\':NONb.            ,dXONM@@MbMXX: 								" << endl;
	cout << "  MOON@M@@MMMM;;:OOONb          ,MX\'\"\':ONMMMMX: 							" << endl;
	cout << "  :NOOM@@MNNN@@X;\"\"XNN@Mb     .dP\"\'   ,..OXM@N: 							" << endl;
	cout << "   MOON@@MMNXXMMO  :M@@M...@o.oN\"\"\":OOOXNNXXOo:								" << endl;
	cout << "   :NOX@@@MNXXXMNo :MMMM@K\"\`,:;NNM@@NXM@MNO;.\'N. 							" << endl;
	cout << "    NO:X@@MNXXX@@O:\'X@@@@MOOOXMM@M@NXXN@M@NOO \'\'b 							" << endl;
	cout << "    \`MO.\'NMNXXN@@N: \'XXM@NMMXXMM@M@XO\"\'\"XM@X;.  :b 						" << endl;
	cout << "     YNO;\'\"NXXXX@M;;::\"XMNN:\"\"ON@@MO: ,;;.:Y@X: :OX. 						" << endl;
	cout << "      Y@Mb;;XNMM@@@NO: \':O: \'OXN@@MO\" ONMMX:\`XO; :X@. 						" << endl;
	cout << "      \'@XMX\':OX@@MN:    ;O;  :OX@MO\" \'OMM@N; \':OO;N@N 					" << endl;
	cout << "       YN;\":.:OXMX\"\': ,:NNO;\';XMMX:  ,;@@MNN.\'.:O;:@X: 					" << endl;
	cout << "       \`@N;;XOOOXO;;:O;:@MOO;:O:\"\" ,oMP@@K\"YM.;NMO;\`NM 					" << endl;
	cout << "        \`@@MN@MOX@@MNMN;@@MNXXOO: ,d@NbMMP\'d@@OX@NO;.\'bb. 					" << endl;
	cout << "       .odMX@@XOOM@M@@XO@MMMMMMNNbN\"YNNNXoNMNMO\"OXXNO..\"\";o. 				" << endl;
	cout << "     .ddMNOO@@XOOM@@XOONMMM@@MNXXMMo;.\"\' .\":OXO \':.\'\"\'\"\'  \'\"\"o. 	" << endl;
	cout << "    \'N@@X;,M@MXOOM@OOON@MM@MXOO:\":ONMNXXOXX:OOO               \"\"ob. 		" << endl;
	cout << "   \')@MP\"\';@@XXOOMMOOM@MNNMOO\"\"   \'\"OXM@MM: :OO.        :...\';o;.;Xb. 	" << endl;
	cout << "  .@@MX\" ;X@@XXOOM@OOXXOO:o:\'      :OXMNO\"\' ;OOO;.:     ,OXMOOXXXOOXMb 	" << endl;
	cout << " ,dMOo:  oO@@MNOON@N:::\"      .    ,;O:\"\"\'  .dMXXO:    ,;OX@XO\"\":ON@M@ 	" << endl;
	cout << ":Y@MX:.  oO@M@NOXN@NO. ..: ,;;O;.       :.OX@@MOO;..   .OOMNMO.;XN@M@P			" << endl;
	cout << ",MP\"OO\'  oO@M@O:ON@MO;;XO;:OXMNOO;.  ,.;.;OXXN@MNXO;.. oOX@NMMN@@@@@M: 		" << endl;
	cout << "\`\' \"O:;;OON@@MN::XNMOOMXOOOM@@MMNXO:;XXNNMNXXXN@MNXOOOOOXNM@NM@@@M@MP 		" << endl;
	cout << "   :XN@MMM@M@M:  :\'OON@@XXNM@M@MXOOdN@@@MM@@@@MMNNXOOOXXNNN@@M@MMMM\"\' 		" << endl;
	cout << "   .oNM@MM@ONO\'   :;ON@@MM@MMNNXXXM@@@@M@PY@@MMNNNNNNNNNNNM@M@M@@P\' 			" << endl;
	cout << "  ;O:OXM@MNOOO.   \'OXOONM@MNNMMXON@MM@@b. \'Y@@@@@@@@@@@@@M@@MP\"\'\" 		" << endl;
	cout << " ;O\':OOXNXOOXX:   :;NMO:\":NMMMXOOX@MN@@@@b.:M@@@M@@@MMM@\"\"\"\" 			" << endl;
	cout << " :: ;\"OOOOOO@N;:  \'ON@MO.\'\":\"\"OOOO@@NNMN@@@. Y@@@MMM@@@@b 				" << endl;
	cout << " :;   \':O:oX@@O;;  ;O@@XO\'   \"oOOOOXMMNMNNN@MN\"\"YMNMMM@@MMo. 				" << endl;
	cout << " :N:.   \'\'oOM@NMo.::OX@NOOo.  ;OOOXXNNNMMMNXNM@bd@MNNMMM@MM@bb 				" << endl;
	cout << "  @;O .  ,OOO@@@MX;;ON@NOOO.. \' \':OXN@NNN@@@@@M@@@@MNXNMM@MMM@, 				" << endl;
	cout << "  M@O;;  :O:OX@@M@NXXOM@NOO:;;:,;;ON@NNNMM\'\`\"@@M@@@@@MXNMMMMM@N 			" << endl;
	cout << "  N@NOO;:oO;O:NMMM@M@OO@NOO;O;oOOXN@NNM@@\'   \`Y@NM@@@@MMNNMM@MM 				" << endl;
	cout << "  ::@MOO;oO:::OXNM@@MXOM@OOOOOOXNMMNNNMNP      \"\"MNNM@@@MMMM@MP 				" << endl;
	cout << "    @@@XOOO\':::OOXXMNOO@@OOOOXNN@NNNNNNNN        \'\`YMM@@@MMM@P\' 			" << endl;
	cout << "    MM@@M:\'\'\'\' O:\":ONOO@MNOOOOXM@NM@NNN@P           \"\`\"\"\"MM\' 		" << endl;
	cout << "    \'\'MM@:     \"\' \'OOONMOYOOOOO@MM@MNNM\" 								" << endl;
	cout << "      YM@\'         :OOMN: :OOOO@MMNOXM\' 										" << endl;
	cout << "      \`:P           :oP\'\'  \"\'OOM@NXNM\' 									" << endl;
	cout << "       \`\'                    \':OXNP\' 										" << endl;
	cout << "                               \'\"\'											" << endl;
	
	cout << "woof" << endl;
}